--table for users

CREATE TABLE tb_users (
    id_user NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    first_lastname VARCHAR2(100),
    second_lastname VARCHAR2(100),
    email VARCHAR2(150) UNIQUE,
    username VARCHAR2(50) UNIQUE,
    password VARCHAR2(255),
    role VARCHAR2(10) CHECK (role IN ('users', 'admin')),
    rut VARCHAR2(12) NOT NULL,
    CONSTRAINT chk_rut_format CHECK (REGEXP_LIKE(rut, '^\d{7,8}-[0-9kK]$'))
);


--table for laboratories
CREATE TABLE tb_laboratories (
    id_laboratory NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nameLaboratory VARCHAR2(100) NOT NULL UNIQUE,
    addressLaboratory VARCHAR2(150) NOT NULL,
    phoneLaboratory VARCHAR2(15) NOT NULL,
    emailLaboratory VARCHAR2(100) NOT NULL,
    websiteLaboratory VARCHAR2(100),
    specialtyLaboratory VARCHAR2(50) NOT NULL,
    CONSTRAINT chk_nameLaboratory_length CHECK (LENGTH(nameLaboratory) >= 4),
    CONSTRAINT chk_addressLaboratory_length CHECK (LENGTH(addressLaboratory) <= 150),
    CONSTRAINT chk_phoneLaboratory_format CHECK (REGEXP_LIKE(phoneLaboratory, '^\+?\d{7,15}$')),
    CONSTRAINT chk_emailLaboratory_format CHECK (REGEXP_LIKE(emailLaboratory, '^[^@]+@[^@]+\.[^@]+$') AND LENGTH(emailLaboratory) BETWEEN 5 AND 100),
    CONSTRAINT chk_websiteLaboratory_length CHECK (websiteLaboratory IS NULL OR LENGTH(websiteLaboratory) <= 100),
    CONSTRAINT chk_specialtyLaboratory_length CHECK (LENGTH(specialtyLaboratory) BETWEEN 2 AND 50)
);